container:
  image: python:3.7.4-alpine3.10

docker_builder:
  only_if: $CIRRUS_TAG != ''
  env:
    DOCKER_USERNAME: ENCRYPTED[d149d37090ee6cbc8d0a4256f8ef817723358d481862867c49b240a9d3b86192abb0aafe59d750794153389b0bcc5ac2]
    DOCKER_PASSWORD: ENCRYPTED[c307b26c6429d650b91becbc08e9c2e88bff51d8d614db900e595812adb722dd7c449902f90a622a4c09ebe35d487bf0]
  build_script: docker build --tag rpkish/botiana:$CIRRUS_TAG .
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push rpkish/botiana:$CIRRUS_TAG
