container:
  image: python:3.7.4-alpine3.10

test_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: cd /usr/local/botiana; echo $PYTHON_VERSION && cat requirements.txt
    populate_script: cd /usr/local/botiana;    pip install -r requirements.txt
  test_script: cd /usr/local/botiana;          pylint *.py
